### ISSUE TITLE
about version of 'SMARTS'

### ISSUE THREAD

**Issue by MarliseLussa** [smarts-project/smarts-project.rl#5]
Please let me know on which version of 'SMARTS' your codes based, THX.

**Comment by Adaickalavan** [comment]
+ Kindly note that ULTRA is not being maintained anymore.
+ Let us know how you intend to use SMARTS and any issues encountered while using SMARTS.
+ Going forward, please post all questions and issues at our main SMARTS [repository](https://github.com/huawei-noah/SMARTS).
